// src/vue/ListBox.vue
<template>
    <ul class="list-group">
        <li 
        :class="{ active: item.id === active.item.id}"
        class="list-group-item" @click="handleItemSelect(item)" v-for="item in items" :key="item.id"> {{ item.name}}</li>
        <li v-if="!items.length" class="list-group-item">No Records</li>
    </ul>
</template>

<script>
export default {
  props: {
    handleItemSelect: {
      type: Function,
      required: true
    },
    items: {
      type: Array,
      required: true
    },
    active: {
      type: Object,
      required: true
    }
  }
};
</script>

// src/react/ListBox.js
import React from "react";

export default ({ items, handleItemSelect, active }) => (
  <ul className="list-group">
    {items.map(item => (
      <li
        key={item.id}
        onClick={handleItemSelect(item)}
        className={`${
          active.item.id === item.id ? "active" : ""
        } list-group-item`}
      >
        {" "}
        {item.name}
      </li>
    ))}
    {!items.length && <li className="list-group-item">No Records</li>}
  </ul>
);
